name: Deploy DevOps Application

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-central-1
  ECR_REPOSITORY: devops-app
  ECS_CLUSTER: devops-app-cluster
  ECS_SERVICE: devops-app-service
  CONTAINER_NAME: devops-app

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      # ==========================================
      # 1. Checkout
      # ==========================================

      - name: Checkout source code
        uses: actions/checkout@v4


      # ==========================================
      # 2. AWS Authentication using OIDC
      # ==========================================

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}


      # ==========================================
      # 3. Login to ECR
      # ==========================================

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2


      # ==========================================
      # 4. Build Docker image
      # ==========================================

      - name: Build Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}

        run: |
          docker build \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            ./app


      # ==========================================
      # 5. Push Docker image
      # ==========================================

      - name: Push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}

        run: |
          docker push \
            $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG


      # ==========================================
      # 6. Set image
      # ==========================================

      - name: Set image URI
        id: image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}

        run: |
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT


      # ==========================================
      # 7. Render ECS task definition
      # ==========================================

      - name: Render ECS task definition
        id: task-def

        uses: aws-actions/amazon-ecs-render-task-definition@v1

        with:
          task-definition: task-definition.json
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.image.outputs.image }}


      # ==========================================
      # 8. Deploy to ECS
      # ==========================================

      - name: Deploy to ECS

        uses: aws-actions/amazon-ecs-deploy-task-definition@v2

        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true